[package]
name = "picky"
version = "4.0.0"
authors = [
    "jtrepanier-devolutions <jtrepanier@devolutions.net>",
    "Benoît CORTIER <benoit.cortier@fried-world.eu>",
]
edition = "2018"

[dependencies]
serde_asn1_der = { git = "https://github.com/Devolutions/serde_asn1_der", features = ["extra_types", "chrono_conversion"] }
oid = { version = "^0.1.1", features = ["serde_support"] }
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
base64 = "0.10"
num-bigint-dig = "0.5"
err-derive = "0.2"
err-ctx = "0.2"

# /!\ ===== cryptography dependencies ===== /!\
# These should be updated as soon as possible.
# /!\ ===================================== /!\

sha-1 = "0.8"
sha2 = "0.8"
rsa = "0.1"
rand = "0.6" # TODO: update to 0.7. Requires rsa crate to support 0.7 too.

[dev-dependencies]
pretty_assertions = "*"
hex = "0.3"
