[package]
name = "picky"
version = "3.0.0"
authors = ["jtrepanier-devolutions <jtrepanier@devolutions.net>"]
edition = "2018"

[dependencies]
mbedtls = { git = "https://github.com/Devolutions/rust-mbedtls.git", branch = "wayk"}
serde_asn1_der = { git = "https://github.com/Devolutions/serde_asn1_der", features = ["extra_types", "chrono_conversion"] }
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
rand = "0.6"
rand_chacha = "0.1"
rand_core = "0.4"
regex = "1.1"
base64 = "0.10"
hex = "0.3"
oid = { version = "^0.1.1", features = ["serde_support"] }

[dev-dependencies]
pretty_assertions = "0.6"
num-bigint-dig = "0.5"
