[package]
name = "picky"
version = "4.1.0"
authors = [
    "jtrepanier-devolutions <jtrepanier@devolutions.net>",
    "Benoît CORTIER <benoit.cortier@fried-world.eu>",
]
edition = "2018"

[dependencies]
serde_asn1_der = { git = "https://github.com/Devolutions/serde_asn1_der", features = ["extra_types"] }
oid = { version = "^0.1.1", features = ["serde_support"] }
serde = "1.0"
serde_derive = "1.0"
base64 = "0.10"
snafu = "0.6"
num-bigint-dig = "0.5" # TODO: remove this dependency

chrono = { version = "0.4", optional = true }

# /!\ ===== cryptography dependencies ===== /!\
# These should be updated as soon as possible.
# /!\ ===================================== /!\

sha-1 = "0.8"
sha2 = "0.8"
rsa = { git = "https://github.com/Devolutions/RSA" }
rand = "0.6" # TODO: update to 0.7. Requires rsa crate to support 0.7 too.

[dev-dependencies]
pretty_assertions = "*"
hex = "0.3"

[features]
default = []
chrono_conversion = ["chrono", "serde_asn1_der/chrono_conversion"]
controller = ["chrono_conversion"]
expose_internals = []
