[package]
name = "picky-server"
version = "4.5.0"
authors = [
    "jtrepanier-devolutions <jtrepanier@devolutions.net>",
    "Benoît CORTIER <benoit.cortier@fried-world.eu>",
    "Johann Dufaud <jdufaud@devolutions.net>",
]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Devolutions/picky-rs"

[dependencies]
picky = { version = "4.5", default-features = false, features = ["x509", "jose", "chrono_conversion"], path = "../picky" }
picky-asn1 = { version = "0.2", path = "../picky-asn1" }
mongodb = { package = "mongodb_cwal", version = "0.6", features = ["ssl"] }
clap = { features = ["yaml"], version = "2.32" }
saphir = { version = "0.9", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
multihash = "0.9"
multibase = "0.7"
bson = "0.14"
log = "0.4"
log4rs = "0.8"
r2d2 = "0.8"
chrono = "0.4"
base64 = "0.10"
hex = "0.3"
snafu = "0.6"
unicase = "2.6"
rand = { version = "0.7", optional = true }

[dev-dependencies]
rand = "0.7"
http = "0.1"

[features]
pre-gen-pk = ["rand"]
