[package]
name = "picky-server"
version = "4.2.1"
authors = [
    "jtrepanier-devolutions <jtrepanier@devolutions.net>",
    "Benoît CORTIER <benoit.cortier@fried-world.eu>",
    "Johann Dufaud <jdufaud@devolutions.net>",
]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Devolutions/picky-rs"

[dependencies]
picky = { version = "4.5", default-features = false, features = ["x509", "chrono_conversion"] }
picky-asn1 = "0.1"
mongodb = { package = "mongodb_cwal", version = "0.6", features = ["ssl"] }
curl = { git = "https://github.com/Devolutions/curl-rust", branch = "wayk" }
clap = { features = ["yaml"], version = "2.32" }
multihash = "0.8"
config = "0.9"
bson = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
log4rs = "0.8"
r2d2 = "0.8"
saphir = { version = "0.9", default-features = false }
portpicker = "0.1"
chrono = "0.4"
base64 = "0.10"
hex = "0.3"
snafu = "0.6"
rand = { version = "0.7", optional = true }

[dev-dependencies]
rand = "0.7"

[features]
pre-gen-pk = ["rand"]
