[package]
name = "picky-server"
version = "3.3.0"
authors = ["jtrepanier-devolutions <jtrepanier@devolutions.net>"]
edition = "2018"

[dependencies]
picky = { path = "../picky" }
mongodb = { git = "https://github.com/Devolutions/mongo-rust-driver-prototype", branch = "master", features = ["ssl"] }
curl = { git = "https://github.com/Devolutions/curl-rust", branch = "wayk" }
clap = { features = ["yaml"], version = "2.32" }
multihash = "0.8"
config = "0.9"
bson = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
log4rs = "0.8"
r2d2 = "0.8"
saphir = "0.9"
portpicker = "0.1"
chrono = "0.4"
base64 = "0.10"
hex = "0.3"

rand = { version = "0.7", optional = true }

[features]
pre-gen-pk = ["rand"]
